Update Blocky documentation
truecharts/website pull request #286
Opened 2023-08-25 19:53 UTC by depasseg

**Description**

⚒️ Fixes  # 

**⚙️ Type of change**

- [X ] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

2023-09-04 16:07 UTC, StevenMcElligott requested changes
Needs to  be the on /charts repo, I'll file

2023-09-05 01:58 UTC, kqmaverick commented on docs/charts/enterprise/blocky/setup-guide.md
> +In the below example I am using Google DNS.  I don't know if you need a bootstrap DNS if you have a UDP server listed above.
```suggestion
In the below example I am using Google DNS.
```

2023-09-05 02:01 UTC, kqmaverick commented on docs/charts/enterprise/blocky/setup-guide.md
> +need to ensure your loadbalancer IP address is set and won't change.
```suggestion
need to setup a static ip address and leave the default setting DNS TCP Service and DNS UDP Service as LoadBalancer.
```

2023-09-05 02:03 UTC, kqmaverick commented on docs/charts/enterprise/blocky/setup-guide.md
> +You need to configure the systems on your network to use the loadbalancer IP address configured above.  This will either be done per system
```suggestion
You need to configure the devices on your network to use the static IP address configured above.  This can be done per device or by changing the DHCP or DNS settings on your router.
```

2023-09-05 02:04 UTC, kqmaverick commented on docs/charts/enterprise/blocky/setup-guide.md
> +or by changing the DHCP settings on your router.
```suggestion
```

2023-09-05 02:05 UTC, kqmaverick commented on docs/charts/enterprise/blocky/setup-guide.md
> +This will guide you through the basic setup of Blocky which is the preferred DNS solution for TrueCharts. This guide will cover basic setup options which will get you up and running and is not all in
```suggestion
This will guide you through the basic setup of Blocky which is the preferred DNS solution for TrueCharts. This guide will cover basic setup options which will get you up and running and is not all inclusive.  Configuring your devices to use Blocky is out of scope of this guide.
```

2023-09-05 02:06 UTC, kqmaverick commented on docs/charts/enterprise/blocky/setup-guide.md
> +Blocky supports 3 methods for upstream DNS.  You can choose multiple options, but I'm not sure if the order matters.
```suggestion
Blocky supports 3 methods for upstream DNS.  You can use any combination of the below.
```

2023-09-27 00:25 UTC, StevenMcElligott commented
Fixed on /charts repo

2023-09-27 00:25 UTC, closed without merging