docs: Adds a backup step to the cobia migration guide
truecharts/website pull request #684
Opened 2024-05-20 03:22 UTC by Shrinks99

**Description**

- Instructs users to backup with HeavyScript prior to updating
- Adds an explicit update step to the guide
- Adds instructions for restoring a CNPG database via the backup as part of the migration script.

Currently no instructions are provided in the migration script for performing a backup with HeavyScript.  I did this before following the guide and it ended up being helpful and required to complete it!  I figure it's best if this is explicitly part of the instructions instead of hoping that they follow general best practices when updating & migrating things.

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

This is a generalization of the steps that I went through when migrating Nextcloud on my personal server.  Instructions given were helpfully provided by @ksimm1 on Discord.

**📃 Notes:**

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [x] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning
- [ ] I made sure the title starts with `feat(chart-name):`, `fix(chart-name):` or `chore(chart-name):`

2024-05-20 07:52 UTC, bitpushr requested changes
TBD

2024-05-21 01:42 UTC, bitpushr commented on src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
> +    Prior to updating to TrueNAS SCALE DragonFish, please ensure that TrueNAS SCALE is updated to the latest version of Cobia (23.10.2), and that all of your TrueCharts apps are fully updated, on the
```suggestion
    Prior to updating to TrueNAS SCALE DragonFish, please ensure that TrueNAS SCALE is updated to the latest version of Cobia (23.10.2), and that all of your TrueCharts apps are fully updated, on the [correct trains]((/news/train-renames) and running or otherwise working correctly.
```

2024-05-21 01:43 UTC, bitpushr commented on src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
> +    Update as usual through TrueNAS' System Settings > Update page.
```suggestion
    Update to DragonFish as usual through TrueNAS' System Settings > Update page.
```

2024-05-21 01:44 UTC, bitpushr commented on src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
> +3. Rerun the migration process and select the backup.
```suggestion
3. Re-run the migration process and select the backup.
```

2024-05-21 01:45 UTC, bitpushr approved these changes

2024-05-21 01:49 UTC, bitpushr commented
Minor fixups and applies a suggestion from #general to link to the news post about prior train name changes since this should also be checked prior to migration.

2024-05-21 02:25 UTC, Shrinks99 commented
Wow that's another good call RE train name changes.  Another thing I had fortunately done a while ago :)

2024-05-21 20:56 UTC, merged