VolSync and CNPG news post
truecharts/website pull request #689
Opened 2024-05-23 05:33 UTC by bitpushr

**Description**

⚒️ Fixes  # 

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning
- [ ] I made sure the title starts with `feat(chart-name):`, `fix(chart-name):` or `chore(chart-name):`

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

2024-05-23 13:38 UTC, Ornias1993 commented on src/content/docs/news/2024-05-25-app-backups-and-restores.md
> +In addition to the above CNPG enhancements, TrueCharts is proud to introduce [VolSync](https://github.com/backube/volsync)'s automatic backup and restore capabilities for PVC containers. VolSync simp
```suggestion
In addition to the above CNPG enhancements, TrueCharts is proud to introduce [VolSync](https://github.com/backube/volsync)'s automatic backup and restore capabilities for PVC storage. VolSync simplifies the process of managing PVC backups, ensuring that your applications’ data is safeguarded.
```

2024-05-23 13:38 UTC, Ornias1993 commented on src/content/docs/news/2024-05-25-app-backups-and-restores.md
> +Currently, this new backup and restore functionality isn't yet functional on TrueNAS SCALE due to an upstream bug with OpenEBS. We've submitted a bug report and will update the docs page linked below
```suggestion
Currently, this new restore functionality isn't yet functional on TrueNAS SCALE due to an upstream bug with OpenEBS. We've submitted a bug report and will update the docs page linked below once this is resolved. For users of our apps on other Helm platforms, this does not apply, so backup and restore functionality should work fine.
```

2024-05-23 13:39 UTC, Ornias1993 requested changes
This needs to move away from the term "apps", Guides that are platform specific need to be referenced as "guide for SCALE" not just "the guide".

Etc.

We're not a SCALE project, we're building Helm-Charts of which SCALE Apps are just one of the downstreams

2024-05-23 22:11 UTC, Ornias1993 commented on src/content/docs/SCALE/guides/backup-restore.md
> +4. We advise you to set the "mode" to `restore`, this should prevent the app starting with an empty database upon restore.
Incorrect, you want to set it to restore beforehand.
Because if you export and import a config, it would take that setting.

after initialisation the setting is inactive, so it should be set to restore after initialisation.

2024-05-25 09:34 UTC, Ornias1993 commented on src/content/docs/SCALE/guides/backup-restore.md
> +title: Backup, Migrations and Restoring on SCALE
```suggestion
title: Backup, Migrations and Restoring
```

2024-05-25 09:34 UTC, Ornias1993 commented on src/content/docs/SCALE/guides/backup-restore.md
> +title: Backup, Migrations and Restoring on SCALE
We're already in the SCALE catagory.
Dont add "on scale" every damn time please

2024-05-26 04:32 UTC, bitpushr commented
Ready to merge whenever we want the news post to go live. Was mainly using this PR and #694 to test working/pushing between branches.

2024-05-26 17:16 UTC, bitpushr commented
Decided to add the SCALE restoration warning on a separate PR instead, sorry. Meant to leave this one just for the news post. See #696

2024-05-29 17:50 UTC, merged