Full example for flux deployment
truecharts/website pull request #793
Opened 2024-08-04 10:27 UTC by nebulans

**Description**
Current example for flux does not give a specification for referenced helm repository.  This makes deploying truecharts charts with flux harder than it should be.

Easy for users to get this wrong with confusion between OCI repositories & Helm repositories with an OCI URL.

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**
Working config copied from my homelab.

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [x] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning
- [ ] I made sure the title starts with `feat(chart-name):`, `fix(chart-name):` or `chore(chart-name):`

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

2024-08-04 10:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/truecharts/website?pullRequest=793) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/truecharts/website?pullRequest=793) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/truecharts/website?pullRequest=793) it.</sub>

2024-08-06 19:11 UTC, bitpushr commented
Looks fine to me, just leaving this for @Ornias1993 to confirm when he has the time.

2024-08-11 19:01 UTC, PrivatePuffin commented on src/content/docs/general/fluxcd.md
> +---
This is JUST describing the helm-release object. Not the helm repository object.,
Your instructions will cause users to brick things by adding a helm repository object for each helm release object.

2024-08-11 19:01 UTC, PrivatePuffin requested changes
.

2024-08-11 19:19 UTC, bitpushr approved these changes

2024-08-11 19:21 UTC, bitpushr approved these changes

2024-08-11 19:21 UTC, merged

2024-08-11 21:24 UTC, PrivatePuffin commented
@bitpushr WTF, why did you merge then when I explicitly vetoed it?!